In [7]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
import astropy.io.fits as fits
import matplotlib

In [5]:
imgFile_sciimg = '/Users/philippe/Data/ZTF/sci/2018/0604/265567/ztf_20180604265567_000761_zg_c14_o_q2_sciimg.fits'
imgFile_mskimg = '/home/nicolas/Work/Data/ztf/sci/2017/1027/284155/ztf_20171027284155_000694_zr_c09_o_q4_mskimg.fits'
fData = fits.open(imgFile_mskimg)
print(fData.info())
fData[0].header

Filename: /home/nicolas/Work/Data/ztf/sci/2017/1027/284155/ztf_20171027284155_000694_zr_c09_o_q4_mskimg.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  4             1 PrimaryHDU     205   (3072, 3080)   int16   
None


SIMPLE  =                    T / Created with PDL (http://pdl.perl.org)         
BITPIX  =                   16                                                  
NAXIS   =                    2                                                  
NAXIS1  =                 3072                                                  
NAXIS2  =                 3080                                                  
BUNIT   = 'Data Value'                                                          
ORIGIN  = 'Zwicky Transient Facility' / Data origin                             
OBSERVER= 'ZTF Robotic Software' / Observer                                     
ROBOSOFT= '0.70-devel October 7, 2017' / Robotic software version               
FITSSOFT= '0.70-devel October 7, 2017' / FITS software version                  
INSTRUME= 'ZTF/MOSAIC'         / Instrument name                                
DETECTOR= '        '           / Detector controller                            
DETSOFT = '        '        

In [8]:
# mskimg data
imgData_mskimg = fits.getdata(imgFile_mskimg)
print(type(imgData_mskimg))
print(imgData_mskimg.shape)
print(imgData_mskimg)
print('Min =', np.min(imgData_mskimg))
print('Max =', np.max(imgData_mskimg))
print('Mean =', np.mean(imgData_mskimg))
print('Std =', np.std(imgData_mskimg))
print('Median =', np.median(imgData_mskimg)) 

fig = plt.figure(figsize=[8,4])
ax  = fig.add_subplot(121)
plt.imshow(imgData_mskimg, interpolation='nearest', origin='lower', cmap='viridis', norm=LogNorm(), vmin=1)
           #norm=LogNorm())
           #vmax=3)
plt.colorbar()
#plt.xlim(0,300)
#plt.ylim(0,300)
plt.show()
ax = fig.add_subplot(122)
plt.hist(imgData_mskimg.flatten(), bins=1000)
#         range=[-500,500])
#plt.xlim(-500,500)
#plt.ylim(0,100)
plt.yscale('log')
plt.show()

<class 'numpy.ndarray'>
(3080, 3072)
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [16  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
Min = 0
Max = 2066
Mean = 1.5140407281520563
Std = 53.95100398153869
Median = 0.0


<IPython.core.display.Javascript object>

NameError: name 'LogNorm' is not defined

# Bit-mask definitions
                                            
- BIT00   =                    0 / AIRCRAFT/SATELLITE TRACK                       
- BIT01   =                    1 / CONTAINS SEXTRACTOR DETECTION                  
- BIT02   =                    2 / LOW RESPONSIVITY                               
- BIT03   =                    3 / HIGH RESPONSIVITY                              
- BIT04   =                    4 / NOISY                                          
- BIT05   =                    5 / GHOST FROM BRIGHT SOURCE                       
- BIT06   =                    6 / GHOST FROM CHARGE SPILLAGE                        
- BIT07   =                    7 / PIXEL SPIKE (POSSIBLE RAD HIT)                 
- BIT08   =                    8 / SATURATED                                      
- BIT09   =                    9 / DEAD (UNRESPONSIVE)                            
- BIT10   =                   10 / NAN (not a number)                             
- BIT11   =                   11 / CONTAINS PSF-EXTRACTED SOURCE POSITION         
- BIT12   =                   12 / HALO FROM BRIGHT SOURCE                        
- BIT13   =                   13 / RESERVED FOR FUTURE USE                        
- BIT14   =                   14 / RESERVED FOR FUTURE USE                        
- BIT15   =                   15 / RESERVED FOR FUTURE USE   

In [10]:
# TESTS
bitmask = 6141
#bitmask = 258
print(bitmask)
print("{:b}".format(bitmask))

# Logical AND
print(bitmask & 6141)
print("{:b}".format(bitmask & 6141))

6141
1011111111101
6141
1011111111101


In [11]:
# Compute a mask image = 0 for good pixels
#                     != 0 for bad pixels
# 6141 = 2^0 + 2^2 + 2^3 + 2^4 + 2^5 + 2^6 + 2^7 + 2^8 + 2^9 + 2^10 + 2^12
imgData_mskbit = imgData_mskimg.copy()
imgData_mskbit = (imgData_mskimg & 0)

# Cleaned image by putting all bad pixels to -99
#imgData_cleanimg = imgData_sciimg.copy()
mask = (imgData_mskbit == 0)
print(type(mask))
print(mask)
            

<class 'numpy.ndarray'>
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]


In [ ]:
# Chi-2 computing with masks on vignetting image 'img' with model 'model'
rms = mask*(img-model)**2
chi2 = np.sum(rms)

In [14]:
len(mask)

3080

In [20]:
mask[mask == False]

array([], dtype=bool)