In [7]:
%matplotlib widget

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import astropy.io.fits as fits
import matplotlib

In [2]:
imgFile_sciimg = '/home/nicolas/Work/Data/ztf/sci/2018/1006/408484/ztf_20181006408484_000695_zr_c12_o_q2_scimrefdiffimg.fits.fz'
imgFile_mskimg = '/home/nicolas/Work/Data/ztf/sci/2018/1006/408484/ztf_20181006408484_000695_zr_c12_o_q2_mskimg.fits'
fData = fits.open(imgFile_mskimg)
print(fData.info())

Filename: /home/nicolas/Work/Data/ztf/sci/2018/1006/408484/ztf_20181006408484_000695_zr_c12_o_q2_mskimg.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  2             1 PrimaryHDU     208   (3072, 3080)   int16   
None


In [25]:
refimg = fits.getdata('/home/nicolas/Work/Data/ztf/ref/001/field001735/zg/ccd02/q2/ztf_001735_zg_c02_q2_refimg.fits')

In [26]:
plt.close()
plt.imshow(refimg)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [24]:
# mskimg data
imgData_mskimg = fits.getdata(imgFile_mskimg)
imgData_sciimg = fits.getdata(imgFile_sciimg)
print(type(imgData_mskimg))
print(imgData_mskimg.shape)
print(imgData_mskimg)
print('Min =', np.min(imgData_mskimg))
print('Max =', np.max(imgData_mskimg))
print('Mean =', np.mean(imgData_mskimg))
print('Std =', np.std(imgData_mskimg))
print('Median =', np.median(imgData_mskimg)) 

plt.close()

fig = plt.figure()
ax  = fig.add_subplot(311)
plt.imshow(imgData_mskimg, interpolation='nearest',
           origin='lower', cmap='viridis',
           norm=matplotlib.colors.LogNorm(), vmin=1)
           #norm=LogNorm())
           #vmax=3)
plt.colorbar()
#plt.xlim(0,300)
#plt.ylim(0,300)
plt.show()
ax = fig.add_subplot(312)
plt.hist(imgData_mskimg.flatten(), bins=1000)
#         range=[-500,500])
#plt.xlim(-500,500)
#plt.ylim(0,100)
plt.yscale('log')
plt.show()
ax = fig.add_subplot(313)
plt.imshow(imgData_sciimg, cmap='viridis', vmin=-15, vmax=15)
plt.show()

<class 'numpy.ndarray'>
(3080, 3072)
[[2 2 2 ... 2 0 0]
 [2 2 2 ... 2 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Min = 0
Max = 2306
Mean = 3.0895106195887445
Std = 78.18628877814218
Median = 0.0


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# Bit-mask definitions
                                            
- BIT00   =                    0 / AIRCRAFT/SATELLITE TRACK                       
- BIT01   =                    1 / CONTAINS SEXTRACTOR DETECTION                  
- BIT02   =                    2 / LOW RESPONSIVITY                               
- BIT03   =                    3 / HIGH RESPONSIVITY                              
- BIT04   =                    4 / NOISY                                          
- BIT05   =                    5 / GHOST FROM BRIGHT SOURCE                       
- BIT06   =                    6 / GHOST FROM CHARGE SPILLAGE                        
- BIT07   =                    7 / PIXEL SPIKE (POSSIBLE RAD HIT)                 
- BIT08   =                    8 / SATURATED                                      
- BIT09   =                    9 / DEAD (UNRESPONSIVE)                            
- BIT10   =                   10 / NAN (not a number)                             
- BIT11   =                   11 / CONTAINS PSF-EXTRACTED SOURCE POSITION         
- BIT12   =                   12 / HALO FROM BRIGHT SOURCE                        
- BIT13   =                   13 / RESERVED FOR FUTURE USE                        
- BIT14   =                   14 / RESERVED FOR FUTURE USE                        
- BIT15   =                   15 / RESERVED FOR FUTURE USE   

In [10]:
# TESTS
bitmask = 6141
#bitmask = 258
print(bitmask)
print("{:b}".format(bitmask))

# Logical AND
print(bitmask & 6141)
print("{:b}".format(bitmask & 6141))

6141
1011111111101
6141
1011111111101


In [11]:
# Compute a mask image = 0 for good pixels
#                     != 0 for bad pixels
# 6141 = 2^0 + 2^2 + 2^3 + 2^4 + 2^5 + 2^6 + 2^7 + 2^8 + 2^9 + 2^10 + 2^12
imgData_mskbit = imgData_mskimg.copy()
imgData_mskbit = (imgData_mskimg & 0)

# Cleaned image by putting all bad pixels to -99
#imgData_cleanimg = imgData_sciimg.copy()
mask = (imgData_mskbit == 0)
print(type(mask))
print(mask)
            

<class 'numpy.ndarray'>
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]


In [10]:
imgData_mskbit = imgData_mskimg.copy()

In [11]:
plt.imshow(imgData_mskimg, interpolation='nearest',
           origin='lower', cmap='viridis',
           norm=matplotlib.colors.LogNorm(), vmin=1)

In [12]:
mask_ = (imgData_mskbit == 0)

In [13]:
mask_

array([[False, False, False, ..., False,  True,  True],
       [False, False, False, ..., False,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [52]:
%matplotlib widget

In [14]:
plt.close()
plt.imshow(mask_*imgData_sciimg)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [31]:
np.shape(imgData_mskimg)

(3080, 3072)

In [29]:
imgData_mskbit_t[imgData_mskbit_t != 0]

array([   2,    2, 2050, ...,    2,    2,    2], dtype=int16)

In [ ]:
# Chi-2 computing with masks on vignetting image 'img' with model 'model'
rms = mask*(img-model)**2
chi2 = np.sum(rms)

In [14]:
len(mask)

3080

In [20]:
mask[mask == False]

array([], dtype=bool)